DROP DATABASE IF EXISTS F1RacingDB;
CREATE DATABASE F1RacingDB;
USE F1RacingDB;

CREATE TABLE Drivers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    POS TINYINT UNSIGNED NOT NULL DEFAULT 0,
    Driver VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    Nationality VARCHAR(4) NOT NULL DEFAULT 'N/A',
    Car VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    PTS decimal(6,3) UNSIGNED NOT NULL DEFAULT 0,
    Year YEAR NOT NULL DEFAULT 0,
    Code CHAR(3) NOT NULL DEFAULT 'XXX'
);

CREATE TABLE Teams (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Pos TINYINT UNSIGNED NOT NULL DEFAULT 0,
    Team VARCHAR(60) NOT NULL DEFAULT 'UNKNOWN',
    PTS decimal(6,3) UNSIGNED NOT NULL DEFAULT 0,
    Year YEAR NOT NULL DEFAULT 0
);

CREATE TABLE Winners (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GrandPrix VARCHAR(60) NOT NULL DEFAULT 'UNKNOWN',
    Date varchar(10) NOT NULL,
    Winner VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    Car VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    Laps TINYINT UNSIGNED NOT NULL DEFAULT 0,
    Time TIME NOT NULL DEFAULT '00:00:00',
    WinnerCode CHAR(3) NOT NULL DEFAULT 'XXX'
);

CREATE TABLE FastestLaps (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GrandPrix VARCHAR(60) NOT NULL DEFAULT 'UNKNOWN',
    Driver VARCHAR(60) NOT NULL DEFAULT 'UNKNOWN',
    Car VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    Time TIME NOT NULL DEFAULT '00:00:00',
    Year YEAR NOT NULL DEFAULT 0,
    Code CHAR(3) NOT NULL DEFAULT 'XXX'
);

CREATE TABLE DriverChangesLog (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    DriverID INT NOT NULL,
    ChangeType VARCHAR(10) NOT NULL,
    ChangeTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

